blank_issues_enabled: false
contact_links:
  - name: private security report
    url: https://github.com/MCEnvision/MCGen-Templates/security/advisories/new
    about: report exploitable vulnerabilities and sensitive security details privately
