name: quality

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  quality:
    permissions:
      actions: read
      contents: read
    uses: MCEnvision/.github/.github/workflows/quality.yml@c5a9c2ee5002d40b20002f543866a19f52a8e3af
    with:
      shared-ref: "c5a9c2ee5002d40b20002f543866a19f52a8e3af"
      gradle-enabled: false
      node-enabled: true
      node-version: "22"
      native-security: true
      enforce-docs-layout: true
